# Generated by Django 5.0.1 on 2024-02-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestInfo',
            fields=[
                ('testId', models.AutoField(primary_key=True, serialize=False)),
                ('SC', models.JSONField(default={})),
                ('SI', models.JSONField(default={})),
                ('OP', models.JSONField(default={})),
            ],
        ),
    ]
