# Generated by Django 5.0.1 on 2024-02-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testinfo',
            name='practitionerName',
            field=models.CharField(default='abhay.phadnis@gmail.com', max_length=50),
        ),
        migrations.AddField(
            model_name='testinfo',
            name='testType',
            field=models.CharField(default='EUM-I', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testinfo',
            name='userName',
            field=models.CharField(default='Asokan', max_length=50),
        ),
    ]
