# Generated by Django 5.0.1 on 2024-01-20 09:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('order', models.IntegerField(default=100000)),
            ],
        ),
    ]
