# Generated by Django 3.2.12 on 2024-01-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='lookup_id',
        ),
        migrations.AddField(
            model_name='new',
            name='adjective',
            field=models.CharField(db_index=True, default='null', editable=False, max_length=30),
        ),
    ]
