# Generated by Django 3.2.12 on 2024-01-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0002_auto_20240121_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='adjective',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AlterField(
            model_name='new',
            name='order',
            field=models.CharField(default='null', max_length=30),
        ),
    ]
