# Generated by Django 3.2.12 on 2024-01-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0003_auto_20240121_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='order',
            field=models.CharField(default='null', max_length=300),
        ),
    ]
