# Generated by Django 3.2.12 on 2024-01-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0004_alter_new_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='adjective',
        ),
        migrations.RemoveField(
            model_name='new',
            name='order',
        ),
        migrations.AddField(
            model_name='new',
            name='Cautious',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='new',
            name='Emotional',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='new',
            name='Gracious',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='new',
            name='Rational',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='new',
            name='Sacrificing',
            field=models.IntegerField(default=0),
        ),
    ]
