# Generated by Django 5.0.1 on 2024-01-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0005_auto_20240121_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emotional', models.JSONField(default={})),
                ('Cautious', models.JSONField(default={})),
                ('Gracious', models.JSONField(default={})),
                ('Sacrificing', models.JSONField(default={})),
                ('Rational', models.JSONField(default={})),
            ],
        ),
        migrations.DeleteModel(
            name='New',
        ),
    ]
